### ISSUE TITLE
Version 3. When will release?

### ISSUE THREAD

**Issue by WarmongeR1** [jkeyes/python-intercom#124]
subj
The last commit into branch version-3 was in March

**Comment by jkeyes** [comment]
@WarmongeR1 I don't know. I'm actively looking at stuff again though, so I hope to have it soon enough. I'll keep you posted.

**Comment by simonklink** [comment]
@jkeyes Any update on the release date for version 3? 

API Keys are deprecated in Jan 2017 and we would really want to switch to personal access tokens before that.

**Comment by jkeyes** [comment]
@simonklink I haven't heard of any issue with the 3.0b3 so I was thinking I'll release 3 this coming weekend.

**Comment by ryankask** [comment]
Should the `Client` keyword argument be called `token` or `access_token` instead of `personal_access_token`? You could obtain a token via the normal OAuth authorisation flow and it seems like it should work.

The [official Ruby client](https://github.com/intercom/intercom-ruby) has a very similar API and it has the following example code in the README:

```ruby
# With an OAuth or Personal Access token:
intercom = Intercom::Client.new(token: 'my_token')
```

**Comment by WarmongeR1** [comment]
@jkeyes when the release version? :)

**Comment by ryankask** [comment]
It looks like new users will no longer be able to create API keys from the start of March instead of the start of February. Existing users will be able to use API keys until an undetermined point in mid 2017: https://medium.com/intercom-developers/update-new-api-key-deprecation-deadline-e5f99818872e#.oukodaogn

**Comment by jkeyes** [comment]
3.0 has been released folks.
